# Generated by Django 3.1.2 on 2020-11-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpproject', '0004_auto_20201113_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completiondate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='minutes_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
