# Generated by Django 3.1.2 on 2020-12-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpproject', '0006_auto_20201207_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='minutes_spent',
            field=models.IntegerField(blank=True, default=0, help_text='Minutes spent working this task', null=True, verbose_name='Time Spent'),
        ),
    ]
