# Generated by Django 3.1.2 on 2020-11-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lkpStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shortname', models.CharField(max_length=4)),
            ],
        ),
    ]
