# Generated by Django 3.1.2 on 2020-11-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpproject', '0002_lkpstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpproject.lkpstatus'),
        ),
    ]
