# Generated by Django 3.1.2 on 2020-12-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpproject', '0007_auto_20201207_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
