# Generated by Django 3.1.2 on 2021-01-18 14:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpproject', '0008_task_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the roadmap', max_length=50, verbose_name='Name')),
                ('startdate', models.DateTimeField(blank=True, null=True, verbose_name='Date Due')),
                ('completiondate', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('creationdate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the timeframe', max_length=50, verbose_name='Name')),
                ('timeframe', models.IntegerField(choices=[(0, 'Annual'), (1, 'Quarterly'), (2, 'Monthly'), (3, 'Weekly')], default=0)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpproject.roadmap', verbose_name='Roadmap')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpproject.task', verbose_name='Goal')),
            ],
        ),
    ]
