# Generated by Django 3.1.2 on 2021-01-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpproject', '0009_roadmap_timeframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeframe',
            old_name='timeframe',
            new_name='period',
        ),
        migrations.RemoveField(
            model_name='timeframe',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='timeframe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpproject.timeframe', verbose_name='Timeframe'),
        ),
    ]
