# Generated by Django 3.1.2 on 2021-01-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpproject', '0010_auto_20210123_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeframe',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpproject.timeframe', verbose_name='Parent'),
        ),
    ]
