# Generated by Django 3.1.2 on 2021-04-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpproject', '0011_timeframe_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, help_text='Details about the task', max_length=500, verbose_name='Description'),
        ),
    ]
